version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: postgres
    restart: always
    hostname: 'nc_postgres'
    networks:
      cloud:
        ipv4_address: 172.19.0.4
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme

  app:
    image: nextcloud:fpm
    restart: always
    networks:
      cloud:
        ipv4_address: 172.19.0.3
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=nc_postgres
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme

  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    networks:
      cloud:
        ipv4_address: 172.19.0.2
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
      
  networks:
    cloud:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.19.0.0/24
                  gateway: 172.19.0.1
